# Generated by Django 5.2 on 2025-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
